---
- name: "Set job identifiers"
  set_fact: 
    template_name: "{{ tower_job_template_name | default('NaN') }}"
    template_id: "{{ tower_job_template_id | default('x') }}"


- block:
  - name: query for {{ remote_ansible_user }} in passwd database
    getent:
      database: passwd
      key: "{{ remote_ansible_user }}"
    register: _getent_query
    ignore_errors: yes

  - name: Assert user {{ remote_ansible_user }} exists
    assert:
      that:
        - _getent_query is failed
      fail_msg: "There was a problem with the username lookup. This usually means {{ remote_ansible_user }} is already in-use."

  - name: Create ansible user - CentOS
    become: true
    user:
      name: "{{ remote_ansible_user }}"
      comment: "Ansible User Account"
      groups: ansiblessh
      password: "{{ remote_ansible_user_password | password_hash('sha512') }}"
      state: present
    when: ansible_facts['distribution'] == "CentOS"
  
  - name: Create ansible user - Ubuntu
    become: true
    user:
      name: "{{ remote_ansible_user }}"
      comment: "Ansible User Account"
      groups: ansiblessh
      password: "{{ remote_ansible_user_password | password_hash('sha512') }}"
      state: present
    register: _new_user
    when: ansible_facts['distribution'] == "Ubuntu" or "Debian"

  - name: add authorized key to user
    authorized_key:
      user: "{{ remote_ansible_user }}"
      state: present
      manage_dir: yes
      key: "{{ remote_ansible_user_publickey }}"
    when: _new_user is not failed

  - name: Add {{ remote_ansible_user }} to sudoers in the /etc/sudoers.d/ directory
    lineinfile:
      path: "/etc/sudoers.d/{{ remote_ansible_user }}"
      line: '{{ remote_ansible_user }} ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'

  rescue:
    - name: "Rescue Failure and Make Error Code"
      set_fact:
        work_notes: | 
          Template: {{ template_name | default('NaN') }}
          Task: {{ ansible_failed_task.name }}
          Error: {{ ansible_failed_result }}
        error_code: "{{ template_id | default('NaN') }}-{{ (ansible_failed_task.name | hash('md5'))[-4:] }}"
    - debug: msg="error_message is {{error_code}}"
    - debug: msg="Worknotes are {{ work_notes }}"

- name: "Set Successful Worknotes"
  set_fact:
    work_notes: "Ansible Automation Successful"
    error_code: "{{ template_id }}-000"
  when:
    - error_code is undefined

- name: Telegram notification
  telegram:
    token: "{{ telegram_token }}"
    chat_id: "{{ telegram_chat_id }}"
    msg: |
      Adding user {{ remote_ansible_user }} to {{ inventory_hostname_short }}
      {{ work_notes }}
      - Tatux Bot